server:
  servlet:
    context-path: /auth/v1/
  port: 8080
# Swagger-UI
springdoc:
  swagger-ui:
    path: /swagger-ui
# CORS
cors:
  path:
    pattern: /**
  allowed:
    origins: "*"
    methods: "*"
    headers: "*"
  allow:
    credentials: false
# JWT
jwt:
  keystore:
    location: /etc/reinno/auth-server/private.p12
    password: ${JWT_KEYSTORE_PASSWORD}
    alias: auth-server
  validity:
    minutes: 8
refresh:
  token:
    validity:
      minutes: 30
    cycle:
      validity:
        minutes: 240
# Multi-factor authentication
mfa:
  cache:
    validity:
      minutes: 3
  allowed:
    discrepancy: 1
  time:
    period:
      seconds: 30
# Database
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
# Logging
logging:
  dir: /var/log/reinno/auth-server
  file:
    name: ${logging.dir}/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %level [%thread] %c{1}: %m%n%ex"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %level [%thread] %c{1}: %m%n%ex"
  level:
    io.reinno: INFO